teste

diff --git a/.github/workflows/comment.yaml b/.github/workflows/comment.yaml
--- a/.github/workflows/comment.yaml
+++ b/.github/workflows/comment.yaml
@@ -121,9 +121,11 @@ jobs:
 
             return "true"
       
-      # - name: Check Approver Team
-      #   if: ${{ steps.check-pr-comments.outputs.result == 'true' }}
-      #   run: 
+      - name: failed approve
+        if: ${{ steps.check-pr-comments.outputs.result == 'false' }}
+        run: 
+          echo "failed approve!"
+          exit 1
   
   detect_namespace:
     if: ${{ github.event.issue.pull_request && github.event.comment.body == '/approve' }}
@@ -131,6 +133,8 @@ jobs:
     steps:
       - name: Detect Namespace
         id: detect_namespace
+        env:
+          GH_TOKEN: ${{ secrets.TOKEN }}
         run: |
           PR_TITLE=$(gh pr view ${{ github.event.issue.number }} --json title -q '.title')
           echo "pr title = $PR_TITLE"
