remove race from go test

diff --git a/.github/workflows/comment.yaml b/.github/workflows/comment.yaml
--- a/.github/workflows/comment.yaml
+++ b/.github/workflows/comment.yaml
@@ -12,137 +12,32 @@ permissions:
   issues: write # Required to post comments
 
 jobs:
-  approve-deploy:
-    if: ${{ github.event.issue.pull_request && (github.event.comment.body == '/approve' || github.event.comment.body == '/deploy-stg') }}
+  check-pr-comments:
     runs-on: ubuntu-latest
-    outputs:
-      VALID: ${{steps.check-pr-comments.outputs.result}}
+    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/deploy-stg' }}
     steps:
-      - name: Check PR Comments for /deploy-stg
-        id: check-pr-comments
-        uses: actions/github-script@v6
-        with:
-          result-encoding: string
-          script: |
-            async function failedApprove(commentId, reason) {
-              await github.rest.issues.deleteComment({
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                comment_id: commentId,
-              });
+      - name: Check Deploy
+        id: check-deploy
+        env:
+          GH_TOKEN: ${{ secrets.TOKEN }}
+        run: |
+          PR_OWNER=$(gh pr view ${{ github.event.issue.number }} --json author -q '.author.login')
+          COMMENT_AUTHOR=${{ github.actor }}
 
-              await github.rest.issues.createComment({
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                issue_number: context.issue.number,
-                body: `[BOT] :x: **Deploy approve failed**: ${reason}`,
-              });
+          if [ "$PR_OWNER" != "$COMMENT_AUTHOR" ]; then
+            echo "::error::The owner of the PR ($PR_OWNER) is not the same as the user who sent the comment ($COMMENT_AUTHOR)."
+            gh pr comment ${{ github.event.issue.number }} --body "[BOT] :x: **Error**: The owner of the PR ($PR_OWNER) is not the same as the user who sent the comment ($COMMENT_AUTHOR)."
+            exit 1
+          fi
 
-              throw reason;
-            }
-
-            async function successApprove(commentId, bypassed = false) {
-              await github.rest.issues.deleteComment({
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                comment_id: commentId,
-              });
-
-              await github.rest.issues.createComment({
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                issue_number: context.issue.number,
-                body: `[BOT]${bypassed ? '[BYPASS]' : ''} :white_check_mark: **Deploy approve success by @${context.payload.comment.user.login}**`,
-              });
-            }
-
-            const prNumber = context.payload.issue.number;
-            const user = context.payload.comment.user.login;
-            const commentID = context.payload.comment.id;
-            const prOwner = context.payload.issue.user.login;
-            const commentBody = "${{github.event.comment.body}}";
-
-            try {
-              await successApprove(commentID, true);
-              return "true"
-
-              if (commentBody == '/deploy-stg') {
-                // Check if the comment is from the bypassed user
-                const maintainerTeam = 'banking-eng-cartao-lideranca-maintainers';
-                const { data: maintainerMembers } = await github.rest.teams.listMembersInOrg({
-                  org: context.repo.owner,
-                  team_slug: maintainerTeam,
-                });
-  
-                const isMaintainer = maintainerMembers.some(member => member.login === user);
-                if (isMaintainer) {
-                  await successApprove(commentID, true);
-                  return "true";
-                }
-              }
-
-              // Fetch all comments from the PR
-              const { data: comments } = await github.rest.issues.listComments({
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                issue_number: prNumber,
-              });
-
-              if (!comments || comments.length === 0) {
-                await failedApprove(commentID, "No comments found on the PR!");
-              }
-
-              const sortedComments = comments
-                .filter(comment => comment.body.trim() === '/deploy-stg' || comment.body.trim() === '/approve')
-                .sort((a, b) => new Date(b.created_at) - new Date(a.created_at));            
-
-              const primeDeployRequest = sortedComments.find(comment => comment.body.trim() === '/deploy-stg');
-              
-              if (!primeDeployRequest) {
-                await failedApprove(commentID, "No deploy request found, drop the approve request!");
-              }
-
-              const deployRequestAmount = sortedComments.filter(comment => comment.body.trim() === '/deploy-stg').length;
-              const approveAmount = sortedComments.filter(comment => comment.body.trim() === '/approve').length;
-              
-              // Deploy Request Amount must be has at least 1
-              if (deployRequestAmount != approveAmount + 1) {
-                await failedApprove(commentID, "Deploy request amount must be 1 more than approve amount. Drop all deploy and approve requests!");
-              }
-
-              // Deploy just can called by the author of the PR
-              if (primeDeployRequest.user.login !== prOwner) {
-                await failedApprove(commentID, `Requestor @${primeDeployRequest.user.login} is not the author of the PR(@prOwner), drop the deploy request!`);
-              }
-
-              // Check if approver and requestor are the same
-              if (approveAmount > 0 && primeDeployRequest.user.login === user) {
-                await failedApprove(commentID, `Requestor ${user} is the same as the approver, drop the deploy request!`);
-              }
-
-              // Check if the approver is in the approver team
-              const approverTeam = 'banking-eng-cartao-lideranca';
-              const { data: teamMembers } = await github.rest.teams.listMembersInOrg({
-                org: context.repo.owner,
-                team_slug: approverTeam,
-              });
-
-              const approver = teamMembers.find(member => member.login === user);
-              if (!approver) {
-                throw `User ${user} is not in the approver team ${approverTeam}`
-              }
-            }catch(e) {
-              core.setFailed(`Error: ${e}`);
-              return "false"
-            }
-
-            await successApprove(commentID);
-            return "true";
+          # Create a comment on the PR indicating that the action is waiting for approval
+          ACTION_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+          gh pr comment ${{ github.event.issue.number }} --body "[BOT] :hourglass: **Waiting Approval** on your action: [Action Link]($ACTION_URL)"
 
   detect_namespace:
-    if: ${{ needs.approve-deploy.outputs.VALID == 'true' }}
     runs-on: ubuntu-latest
-    needs: [approve-deploy]
+    # if: ${{ needs.approve-deploy.outputs.VALID == 'true' }}
+    # needs: [approve-deploy]
     outputs:
       APPLICATION_JSON_LIST: ${{ steps.detect_namespace.outputs.APPLICATION_JSON_LIST }}
       NAMESPACE: ${{ steps.detect_namespace.outputs.NAMESPACE }}
