teste

diff --git a/.github/workflows/comment.yaml b/.github/workflows/comment.yaml
--- a/.github/workflows/comment.yaml
+++ b/.github/workflows/comment.yaml
@@ -148,4 +148,38 @@ jobs:
             echo "::error::Namespace '$NAMESPACE' does not exist as a folder in ./internal."
             exit 1
           fi
-          echo "namespace=$NAMESPACE" >> $GITHUB_OUTPUT
+
+          # Search for subfolders in the chart folder that start with $NAMESPACE and extract only the folder names
+          MATCHING_FOLDERS=$(find ./chart -type d -name "${NAMESPACE}*" -exec basename {} \;)
+
+          if [ -z "$MATCHING_FOLDERS" ]; then
+            echo "::error::No subfolders in the chart folder start with namespace '$NAMESPACE'."
+            exit 1
+          fi
+
+          # Transform MATCHING_FOLDERS into a JSON list and add "bank-" as a prefix to each folder
+          APPLICATION_JSON_LIST=$(echo "$MATCHING_FOLDERS" | awk '{print "\"bank-" $0 "\""}' | paste -sd, -)
+          APPLICATION_JSON_LIST="[$APPLICATION_JSON_LIST]"
+          echo "Transformed JSON list: $APPLICATION_JSON_LIST"
+
+          echo "APPLICATION_JSON_LIST=$APPLICATION_JSON_LIST" >> $GITHUB_OUTPUT
+          echo "NAMESPACE=$NAMESPACE" >> $GITHUB_OUTPUT
+  
+  prepare-deploy:
+    if: ${{ success() }}
+    runs-on: ubuntu-latest
+    needs: [approve-deploy, detect_namespace]
+    strategy:
+      matrix:
+        application: ${{ fromJson(needs.detect_namespace.outputs.APPLICATION_JSON_LIST) }}
+    steps:
+      - name: Prepare Deploy
+        id: prepare_deploy
+        env:
+          GH_TOKEN: ${{ secrets.TOKEN }}
+        run: |
+          echo "application : ${{ matrix.application }}"
+          echo "namespace : ${{ needs.detect_namespace.outputs.NAMESPACE }}"
+
+  
+  
